# Generated by Django 6.0.6 on 2026-06-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='puntuacion',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comision',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='comision',
            name='valor_comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado_validacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='limite_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='valor_base_sector',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('PEDIDO', 'Pedido'), ('PAGO', 'Pago'), ('STOCK', 'Stock'), ('SISTEMA', 'Sistema')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo'), ('PASARELA', 'Pasarela de pago')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('PAGADO', 'Pagado'), ('EN_PREPARACION', 'En preparación'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=30),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='tipo',
            field=models.CharField(choices=[('ANUAL', 'Pago anual'), ('COMISION', 'Por comisión')], default='ANUAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='vendedores',
            field=models.ManyToManyField(blank=True, related_name='tutoriales_consultados', to='comercial.vendedor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('EMPRESA', 'Empresa'), ('VENDEDOR', 'Vendedor')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='estado_validacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nivel',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('BRONCE', 'Bronce'), ('PLATA', 'Plata'), ('ORO', 'Oro'), ('ESTRELLA', 'Vendedor estrella')], default='NUEVO', max_length=30),
        ),
    ]
